FROM ubuntu:focal

# Install softwares from apt repo
RUN apt-get update && apt-get install -y \
    libbz2-dev liblzma-dev python3 python3-setuptools python3-pip \
    && rm -rf /var/lib/apt/lists/*

# Make directory for all softwares
#RUN mkdir /software
#WORKDIR /software
#ENV PATH="/software:${PATH}"

# Install system/math python packages (python3)
RUN pip3 install --no-cache-dir deeptools